set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
# Optional chainload support: only use the provided toolchain if explicitly set.
if(DEFINED ENV{GRINPP_CHAINLOAD_TOOLCHAIN} AND NOT "$ENV{GRINPP_CHAINLOAD_TOOLCHAIN}" STREQUAL "")
    set(_GRINPP_ARM_CHAINLOAD "$ENV{GRINPP_CHAINLOAD_TOOLCHAIN}")
    if(EXISTS "${_GRINPP_ARM_CHAINLOAD}")
        set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${_GRINPP_ARM_CHAINLOAD}")
    endif()
endif()
